- src/main/java/org/recap/route/ETLRouteBuilder.java
Added the parallel processing in camel.
> Added the parallel processing in camel.

- src/main/java/org/recap/model/jpa/BibliographicEntity.java
- src/main/java/org/recap/model/jpa/BibliographicHoldingsEntity.java
- src/main/java/org/recap/model/jpa/BibliographicItemEntity.java
- src/main/java/org/recap/model/jpa/ItemEntity.java
- src/main/java/org/recap/repository/BibliographicHoldingsDetailsRepository.java
- src/main/java/org/recap/repository/BibliographicItemDetailsRepository.java
- src/main/resources/application.properties
- src/test/java/org/recap/BaseTestCase.java
- src/test/java/org/recap/model/jpa/BibliographicEntityTest.java
Fixed the issue with composite primary key between bib/holdings/items.
> Fixed the issue with composite primary key between bib/holdings/items.

- src/main/java/org/recap/route/RecordProcessor.java
- src/main/java/org/recap/util/BibSynchronzePersistanceUtil.java
Added the synchronized method for saving bib entities to avoid unique constraint issue.
>  Added the synchronized method for saving bib entities to avoid unique constraint issue.

- src/main/java/org/recap/ReCAPCamelContext.java
- src/main/java/org/recap/model/etl/BibPersisterCallable.java
- src/main/java/org/recap/repository/CollectionGroupDetailsRepository.java
- src/main/java/org/recap/route/ETLRouteBuilder.java
- src/main/java/org/recap/route/RecordProcessor.java
Modified the code to populate collectionGroupId and ItemStatusId.
> Modified the code to populate collectionGroupId and ItemStatusId.

- src/test/java/org/recap/model/jpa/BibliographicEntityTest.java
Added the testcase to refresh object after save.
> Added the testcase to refresh object after save.

- src/main/java/org/recap/model/jpa/BibliographicEntity.java
- src/main/java/org/recap/repository/BibliographicDetailsRepository.java
Modified for enable saveAndFlush option.
> Modified for enable saveAndFlush option.

- src/main/resources/application-tst.properties
Added application properties for tst env
> Added application properties for tst env

- src/main/java/org/recap/repository/XmlRecordRepository.java
- src/main/java/org/recap/route/EtlDataLoadProcessor.java
Updated the data load processor to get the count based on the xmlFileName given.
> Updated the data load processor to get the count based on the xmlFileName given.

- src/test/java/org/recap/controller/EtlDataLoadControllerTest.java
- src/test/java/org/recap/model/etl/BibPersisterCallableTest.java
> Fixes for the test cases

- src/main/java/org/recap/model/jpa/EtlGfaEntity.java
- src/main/java/org/recap/repository/EtlGfaRepository.java
- src/test/java/org/recap/model/jpa/EtlGfaEntityTest.java
> Added EtlGfaEntity

- src/main/java/org/recap/repository/EtlGfaRepository.java
- src/test/java/org/recap/model/jpa/EtlGfaEntityTest.java
Added method to EtlGfaTestcase
> Added method to EtlGfaTestcase

- build.gradle
- src/main/resources/application-junit.properties
- src/test/java/org/recap/controller/EtlDataLoadControllerUT.java
- src/test/java/org/recap/model/etl/BibPersisterCallableUT.java
- src/test/java/org/recap/model/etl/UnicodeRecordSaveUT.java
- src/test/java/org/recap/model/jaxb/JAXBHandlerUT.java
- src/test/java/org/recap/model/jpa/BibliographicEntityUT.java
- src/test/java/org/recap/model/jpa/EtlGfaEntityUT.java
- src/test/java/org/recap/repository/BibliographicDetailsRepositoryUT.java
- src/test/java/org/recap/repository/CollectionGroupDetailsRepositoryUT.java
- src/test/java/org/recap/repository/InstitutionDetailsRepositoryUT.java
- src/test/java/org/recap/repository/ItemDetailsRepositoryUT.java
- src/test/java/org/recap/repository/ItemStatusDetailsRepositoryUT.java
- src/test/java/org/recap/repository/XmlRecordRepositoryUT.java
- src/test/java/org/recap/route/CamelJdbcUT.java
- src/test/java/org/recap/route/FTPRouteBuilderUT.java
- src/test/java/org/recap/route/JMSUT.java
- src/test/java/org/recap/route/ProcessETLUT.java
Added the cobertura plugin and updated the db url in application junit properties
> Added the cobertura plugin and updated the db url in application junit properties

- build.gradle
- src/test/java/org/recap/repository/XmlRecordRepositoryUT.java
Added configuration to accept systemproperties during test
> Added configuration to accept systemproperties during test

- src/test/java/org/recap/model/jpa/BibliographicEntityUT.java
Commented duplicateBibsWithDifferentItems test
> Commented duplicateBibsWithDifferentItems test

- src/test/java/org/recap/model/etl/UnicodeRecordSaveUT.java
Added character set while getting and setting the content
> Added character set while getting and setting the content

- src/test/java/org/recap/model/etl/BibPersisterCallableUT.java
Ignored checkDataTruncateIssue test case in BibPersisterCallableUT
> Ignored checkDataTruncateIssue test case in BibPersisterCallableUT

- src/main/resources/application-junit.properties
Update the keys location for ftp in junit properties
> Update the keys location for ftp in junit properties

- src/main/java/org/recap/model/jpa/ReportEntity.java
> Added Report entity.

- src/main/java/org/recap/repository/ReportDetailRepository.java
- src/test/java/org/recap/repository/ReportDetailRepositoryTest.java
Added repository and test case for report entity
> Added repository and test case for report entity

- src/main/java/org/recap/util/CSVReportHelperUtil.java
- src/test/java/org/recap/model/csv/FailureReportReCAPCSVRecordTest.java
Created the util to prepare the csv failure report object
> Created the util to prepare the csv failure report object

- build.gradle
Added sonar.projectName property
> Added sonar.projectName property

- build.gradle
- src/main/java/org/recap/RecapConstants.java
- src/main/java/org/recap/executors/ExportDataDumpExecutorService.java
- src/main/java/org/recap/model/etl/ExportDataDumpCallable.java
- src/main/java/org/recap/model/export/DataDumpRequest.java
- src/main/java/org/recap/model/jaxb/JAXBHandler.java
- src/main/java/org/recap/route/FtpDataDumpRouteBuilder.java
- src/main/java/org/recap/util/DataDumpUtil.java
- src/main/resources/application-dev.properties
- src/main/resources/application-junit.properties
- src/main/resources/application-local.properties
- src/main/resources/application-tst.properties
- src/test/java/org/recap/dump/BibDataDumpUT.java
Added for exporting data dump - RECAP-116, RECAP-121
> Added for exporting data dump - RECAP-116, RECAP-121

- src/main/java/org/recap/ReCAPConstants.java
- src/main/java/org/recap/camel/FtpDataDumpRouteBuilder.java
- src/main/java/org/recap/controller/DataDumpRestController.java
- src/main/java/org/recap/executors/ExportDataDumpExecutorService.java
- src/main/java/org/recap/model/etl/ExportDataDumpCallable.java
- src/main/java/org/recap/model/export/DataDumpRequest.java
- src/main/java/org/recap/repository/BibliographicDetailsRepository.java
- src/main/java/org/recap/util/DateUtil.java
- src/test/java/org/recap/controller/BaseControllerUT.java
- src/test/java/org/recap/controller/DataDumpRestControllerUT.java
- src/test/java/org/recap/dump/BibDataDumpUT.java
- src/test/java/org/recap/util/DateUtilUT.java
Incremental datadump code changes
> Incremental datadump code changes

- src/main/java/org/recap/ReCAPConstants.java
- src/main/java/org/recap/controller/DataDumpRestController.java
- src/main/java/org/recap/executors/ExportDataDumpExecutorService.java
- src/main/java/org/recap/model/export/DataDumpRequest.java
- src/main/resources/application-dev.properties
- src/main/resources/application-junit.properties
- src/main/resources/application-local.properties
- src/main/resources/application-tst.properties
- src/test/java/org/recap/dump/ExportDataDumpExecutorServiceUT.java
Added noOfThreads and batchSize in application property file
> Added noOfThreads and batchSize in application property file

- src/main/resources/application-junit.properties
Added ftp.datadump.remote.server property in junit application property file
> Added ftp.datadump.remote.server property in junit application property file

- src/main/java/org/recap/executors/ExportDataDumpExecutorService.java
- src/test/java/org/recap/controller/DataDumpRestControllerUT.java
- src/test/java/org/recap/dump/ExportDataDumpExecutorServiceUT.java
> Fixes for data dump testcases

- src/main/java/org/recap/ReCAPConstants.java
- src/main/java/org/recap/controller/DataDumpRestController.java
- src/main/java/org/recap/executors/ExportDataDumpExecutorService.java
- src/main/java/org/recap/model/etl/ExportDataDumpCallable.java
- src/main/resources/application-dev.properties
- src/main/resources/application-junit.properties
- src/main/resources/application-local.properties
- src/main/resources/application-tst.properties
- src/test/java/org/recap/controller/DataDumpRestControllerUT.java
- src/test/java/org/recap/executors/ExportDataDumpExecutorServiceUT.java
Modified code to make institution code mandatory for full export - RECAP-170
> Modified code to make institution code mandatory for full export - RECAP-170

- src/main/java/org/recap/ReCAPConstants.java
- src/main/java/org/recap/controller/DataDumpRestController.java
Update the response code to 400 if there is a internal server error
> Update the response code to 400 if there is a internal server error

- src/main/java/org/recap/ReCAPConstants.java
- src/main/java/org/recap/controller/DataDumpRestController.java
- src/main/java/org/recap/executors/ExportDataDumpExecutorService.java
- src/main/java/org/recap/model/etl/ExportDataDumpCallable.java
- src/main/java/org/recap/model/export/DataDumpRequest.java
- src/main/java/org/recap/util/DateUtil.java
- src/test/java/org/recap/controller/DataDumpRestControllerUT.java
- src/test/java/org/recap/executors/ExportDataDumpExecutorServiceUT.java
- src/test/java/org/recap/repository/BibliographicDetailsRepositoryUT.java
- src/test/java/org/recap/util/DateUtilUT.java
Added transmission type,datetime retrieval for incremental export
> Added transmission type,datetime retrieval for incremental export

- src/main/java/org/recap/executors/ExportDataDumpExecutorService.java
- src/test/java/org/recap/executors/ExportDataDumpExecutorServiceUT.java
- src/test/java/org/recap/repository/BibliographicDetailsRepositoryUT.java
Updated the datetime pattern while getting the record count
> Updated the datetime pattern while getting the record count

- src/main/resources/application-dev.properties
- src/main/resources/application-junit.properties
- src/main/resources/application-local.properties
- src/main/resources/application-tst.properties
- src/main/resources/application-uat.properties
> Updated the ftp port

- src/main/java/org/recap/ReCAPConstants.java
- src/main/java/org/recap/camel/DataDumpFileSystemRouteBuilder.java
- src/main/java/org/recap/camel/DataDumpFtpRouteBuilder.java
- src/main/java/org/recap/controller/swagger/DataDumpRestController.java
- src/main/java/org/recap/executors/ExportDataDumpExecutorService.java
- src/main/java/org/recap/model/export/DataDumpRequest.java
- src/main/java/org/recap/repository/BibliographicDetailsRepository.java
- src/main/java/org/recap/util/DataDumpUtil.java
- src/main/resources/application-junit.properties
- src/test/java/org/recap/controller/DataDumpRestControllerUT.java
- src/test/java/org/recap/util/DataDumpUtilUT.java
Fixed private collection group issue
> Fixed private collection group issue

- src/main/java/org/recap/ReCAPConstants.java
- src/main/java/org/recap/camel/DataDumpReportFileSystemRouteBuilder.java
- src/main/java/org/recap/camel/DataDumpReportFtpRouteBuilder.java
- src/main/java/org/recap/executors/ExportDataDumpExecutorService.java
Modified to generate report for data dump
> Modified to generate report for data dump

- src/main/java/org/recap/controller/swagger/DataDumpRestController.java
Added condition to generate to export data for fetchtype - increment and transmissiontype - filesystem
> Added condition to generate to export data for fetchtype - increment and transmissiontype - filesystem

- build.gradle
- src/main/java/org/recap/ReCAPConstants.java
- src/main/java/org/recap/camel/DataDumpZipFileRouteBuilder.java
- src/main/java/org/recap/camel/DataDumpZipFileToFtpRouteBuilder.java
- src/main/java/org/recap/controller/swagger/DataDumpRestController.java
- src/main/java/org/recap/executors/ExportDataDumpExecutorService.java
- src/test/java/org/recap/camel/DataDumpZipFileRouteBuilderUT.java
- src/test/java/org/recap/camel/DataDumpZipFileToFtpRouteBuilderUT.java
- src/test/java/org/recap/executors/ExportDataDumpExecutorServiceUT.java
Added changes for Zipping the data dump files
> Added changes for Zipping the data dump files

- src/main/java/org/recap/ReCAPConstants.java
- src/main/java/org/recap/camel/DataDumpZipFileRouteBuilder.java
- src/main/java/org/recap/camel/DataDumpZipFileToFtpRouteBuilder.java
- src/main/java/org/recap/executors/ExportDataDumpExecutorService.java
- src/test/java/org/recap/camel/DataDumpZipFileRouteBuilderUT.java
- src/test/java/org/recap/camel/DataDumpZipFileToFtpRouteBuilderUT.java
- src/test/java/org/recap/executors/ExportDataDumpExecutorServiceUT.java
Added datetime changes for datadump files and folder
> Added datetime changes for datadump files and folder

- src/main/java/org/recap/ReCAPConstants.java
- src/main/java/org/recap/camel/DataDumpZipFileRouteBuilder.java
- src/main/java/org/recap/camel/DataDumpZipFileToFtpRouteBuilder.java
- src/main/java/org/recap/controller/swagger/DataDumpRestController.java
- src/main/java/org/recap/executors/ExportDataDumpExecutorService.java
- src/main/resources/application-dev.properties
- src/main/resources/application-junit.properties
- src/main/resources/application-local.properties
- src/main/resources/application-tst.properties
- src/main/resources/application-uat.properties
- src/test/java/org/recap/camel/DataDumpZipFileRouteBuilderUT.java
- src/test/java/org/recap/camel/DataDumpZipFileToFtpRouteBuilderUT.java
- src/test/java/org/recap/executors/ExportDataDumpExecutorServiceUT.java
Added record response limit for transmission type http
> Added record response limit for transmission type http

- README.md
Added Browserstack logo and link
> Added Browserstack logo and link

- src/main/java/org/recap/controller/swagger/DataDumpRestController.java
> Modified for jira RECAP-219

- src/main/java/org/recap/ReCAPConstants.java
- src/main/java/org/recap/service/executor/datadump/AbstractDataDumpExecutorService.java
- src/main/java/org/recap/service/transmission/datadump/DataDumpFileSystemTranmissionService.java
- src/main/java/org/recap/service/transmission/datadump/DataDumpFtpTransmissionService.java
- src/main/java/org/recap/service/transmission/datadump/DataDumpTransmissionInterface.java
- src/main/java/org/recap/service/transmission/datadump/DataDumpTransmissionService.java
- src/test/java/org/recap/camel/datadump/DataDumpZipFileRouteBuilderUT.java
- src/test/java/org/recap/service/executor/datadump/FullDataDumpExecutorServiceUT.java
- src/test/java/org/recap/service/transmission/datadump/DataDumpFileSystemTranmissionServiceUT.java
- src/test/java/org/recap/service/transmission/datadump/DataDumpFtpTransmissionServiceUT.java
Added changes for zipping all files
> Added changes for zipping all files

- src/main/resources/application-dev.properties
- src/main/resources/application-junit.properties
- src/main/resources/application-local.properties
- src/main/resources/application-tst.properties
- src/main/resources/application-uat.properties
> Added the email config info

- src/test/java/org/recap/camel/datadump/ActiveMQRouteBuilderUT.java
> Test for activemq

- src/main/java/org/recap/ReCAPConstants.java
- src/main/java/org/recap/service/executor/datadump/AbstractDataDumpExecutorService.java
- src/main/java/org/recap/service/executor/datadump/IncrementalDataDumpExecutorService.java
- src/test/java/org/recap/util/DataDumpSolrServiceTest.java
Updated changes for incremental
> Updated changes for incremental

- src/main/java/org/recap/service/executor/datadump/AbstractDataDumpExecutorService.java
- src/main/resources/application-local.properties
- src/test/java/org/recap/util/DataDumpSolrServiceTest.java
> FIx for incremental

- src/main/java/org/recap/ReCAPConstants.java
- src/main/java/org/recap/camel/datadump/FileFormatProcessorForDataExport.java
- src/main/java/org/recap/camel/datadump/FileNameProcessorForDataExport.java
- src/main/java/org/recap/camel/datadump/ZipFileProcessor.java
- src/main/java/org/recap/camel/datadump/callable/DeletedRecordPreparerCallable.java
- src/main/java/org/recap/camel/datadump/consumer/DeletedJsonFormatActiveMQConsumer.java
- src/main/java/org/recap/camel/datadump/consumer/DeletedRecordFormatActiveMQConsumer.java
- src/main/java/org/recap/camel/datadump/consumer/MarcXMLFormatActiveMQConsumer.java
- src/main/java/org/recap/camel/datadump/consumer/SCSBXMLFormatActiveMQConsumer.java
- src/main/java/org/recap/camel/datadump/routebuilder/DataExportRouteBuilder.java
- src/main/java/org/recap/model/export/DeletedRecord.java
- src/main/java/org/recap/model/search/SearchRecordsRequest.java
- src/main/java/org/recap/service/executor/datadump/AbstractDataDumpExecutorService.java
- src/main/java/org/recap/service/formatter/datadump/DeletedJsonFormatterService.java
- src/main/java/org/recap/service/preprocessor/DataDumpExportService.java
- src/test/java/org/recap/camel/CamelJdbcUT.java
Deleted Record Json format changes
> Deleted Record Json format changes

- src/main/resources/application-dev.properties
- src/main/resources/application-junit.properties
- src/main/resources/application-tst.properties
- src/main/resources/application-uat.properties
update datadump.marc.nypl property
> update datadump.marc.nypl property

- src/main/resources/application-dev.properties
- src/main/resources/application-junit.properties
- src/main/resources/application-local-container.properties
- src/main/resources/application-tst.properties
- src/main/resources/application-uat.properties
> Updated the properties

- src/main/java/org/recap/camel/EmailPayLoad.java
- src/main/java/org/recap/camel/datadump/DataExportEmailProcessor.java
- src/main/java/org/recap/camel/datadump/ZipFileProcessor.java
- src/main/java/org/recap/camel/datadump/consumer/DeletedJsonFormatActiveMQConsumer.java
- src/main/java/org/recap/camel/datadump/consumer/SCSBXMLFormatActiveMQConsumer.java
- src/main/java/org/recap/camel/datadump/routebuilder/DataExportRouteBuilder.java
- src/main/java/org/recap/service/email/datadump/DataDumpEmailService.java
- src/main/java/org/recap/service/executor/datadump/AbstractDataDumpExecutorService.java
- src/main/java/org/recap/service/executor/datadump/DeletedDataDumpExecutorService.java
- src/main/resources/org/recap/camel/email_body.vm
- src/test/java/org/recap/camel/CamelJdbcUT.java
- src/test/resources/org/recap/camel/email_body.vm
updated email for failure, added datadump report for scsb xml and deleted json
> updated email for failure, added datadump report for scsb xml and deleted json

- src/main/java/org/recap/service/formatter/datadump/MarcXmlFormatterService.java
- src/test/java/org/recap/service/formatter/datadump/MarcXmlFormatterServiceUT.java
- src/test/java/org/recap/service/formatter/datadump/SCSBXmlFormatterServiceUT.java
Updated the 876 tag formation for marc xml generation
> Updated the 876 tag formation for marc xml generation

- src/main/java/org/recap/service/formatter/datadump/SCSBXmlFormatterService.java
Prefixed SCSB with the value of control field 001
> Prefixed SCSB with the value of control field 001

- src/main/java/org/recap/camel/datadump/callable/BibRecordPreparerCallable.java
- src/main/java/org/recap/camel/datadump/consumer/SCSBRecordFormatActiveMQConsumer.java
- src/main/java/org/recap/camel/datadump/routebuilder/DataExportRouteBuilder.java
- src/main/java/org/recap/service/formatter/datadump/SCSBXmlFormatterService.java
Added code for processFailures - scsbformat
> Added code for processFailures - scsbformat

- src/main/java/org/recap/camel/datadump/DataExportEmailProcessor.java
- src/main/java/org/recap/camel/datadump/ZipFileProcessor.java
- src/main/java/org/recap/camel/datadump/consumer/MarcXMLFormatActiveMQConsumer.java
- src/main/java/org/recap/camel/datadump/routebuilder/DataExportRouteBuilder.java
Updated the EmailProcessos for record counts
> Updated the EmailProcessos for record counts

- src/main/java/org/recap/ReCAPConstants.java
- src/main/java/org/recap/controller/swagger/DataDumpRestController.java
- src/main/java/org/recap/service/executor/datadump/AbstractDataDumpExecutorService.java
- src/main/java/org/recap/service/preprocessor/DataDumpExportService.java
Fixed the http transmission type export message for more than 100 records
> Fixed the http transmission type export message for more than 100 records

- src/main/java/org/recap/service/preprocessor/DataDumpExportService.java
> Fixed response entity issue

- src/main/java/org/recap/ReCAPConstants.java
- src/main/java/org/recap/service/executor/datadump/AbstractDataDumpExecutorService.java
- src/main/java/org/recap/service/preprocessor/DataDumpExportService.java
RECAP-301 - Fix to display no data message when there is not data to export
> RECAP-301 - Fix to display no data message when there is not data to export

- src/test/java/org/recap/service/formatter/datadump/MarcXmlFormatterServiceUT.java
Updated the testcase according to the latest change
> Updated the testcase according to the latest change

- src/main/java/org/recap/ReCAPConstants.java
- src/main/java/org/recap/camel/EmailRouteBuilder.java
- src/main/java/org/recap/camel/datadump/DataExportEmailProcessor.java
- src/main/java/org/recap/service/email/datadump/DataDumpEmailService.java
- src/main/java/org/recap/service/preprocessor/DataDumpExportService.java
- src/main/resources/application-dev.properties
- src/main/resources/application-junit.properties
- src/main/resources/application-local-container.properties
- src/main/resources/application-local.properties
- src/main/resources/application-tst.properties
- src/main/resources/application-uat.properties
- src/main/resources/org/recap/camel/no_data_email_body.vm
RECAP-306 - Send email when then is no data to export for ftp
> RECAP-306 - Send email when then is no data to export for ftp

- src/main/java/org/recap/service/formatter/datadump/MarcXmlFormatterService.java
- src/test/java/org/recap/service/formatter/datadump/MarcXmlFormatterServiceUT.java
RECAP-307 - Tag formation for 852, 866 and 876
> RECAP-307 - Tag formation for 852, 866 and 876

- src/main/java/org/recap/service/formatter/datadump/MarcXmlFormatterService.java
RECAP-307 - Updated subfields for 852 and 876
> RECAP-307 - Updated subfields for 852 and 876

- src/main/java/org/recap/controller/swagger/DataDumpRestController.java
- src/main/java/org/recap/service/preprocessor/DataDumpExportService.java
Added changes to expose data dump api via scsb project
> Added changes to expose data dump api via scsb project

- src/main/java/org/recap/ReCAPConstants.java
- src/main/java/org/recap/model/etl/BibPersisterCallable.java
- src/main/java/org/recap/model/jpa/BibliographicEntity.java
- src/main/java/org/recap/model/jpa/ItemEntity.java
- src/main/java/org/recap/model/jpa/ItemPK.java
RECAP-386 - Set cataloging status to complete during initial accession - ETL Load
> RECAP-386 - Set cataloging status to complete during initial accession - ETL Load

- src/main/java/org/recap/model/jaxb/Bib.java
- src/main/java/org/recap/model/jaxb/MatchingInstitutionBibIdType.java
- src/main/java/org/recap/service/formatter/datadump/SCSBXmlFormatterService.java
RECAP-391 - Added MatchingInstitutionBibId in scsb xml format
> RECAP-391 - Added MatchingInstitutionBibId in scsb xml format

- src/main/java/org/recap/camel/datadump/consumer/DeletedJsonFormatActiveMQConsumer.java
- src/main/java/org/recap/camel/datadump/consumer/MarcXMLFormatActiveMQConsumer.java
- src/main/java/org/recap/camel/datadump/consumer/SCSBXMLFormatActiveMQConsumer.java
- src/main/java/org/recap/service/executor/datadump/AbstractDataDumpExecutorService.java
- src/main/java/org/recap/service/preprocessor/DataDumpExportService.java
RECAP-407 - Fixed the empty string date issue for datadump
> RECAP-407 - Fixed the empty string date issue for datadump

- src/main/java/org/recap/ReCAPConstants.java
- src/main/java/org/recap/model/etl/BibPersisterCallable.java
- src/main/java/org/recap/model/jpa/BibliographicEntity.java
- src/main/java/org/recap/service/executor/datadump/IncrementalDataDumpExecutorService.java
- src/main/java/org/recap/service/formatter/datadump/MarcXmlFormatterService.java
- src/main/java/org/recap/service/formatter/datadump/SCSBXmlFormatterService.java
RECAP-415 - Fix for incremental dump
> RECAP-415 - Fix for incremental dump

- src/main/java/org/recap/ReCAPConstants.java
- src/main/java/org/recap/model/jpa/MatchingInstitutionBibViewEntity.java
- src/main/java/org/recap/repository/MatchingInstitutionBibRepository.java
- src/main/java/org/recap/repository/ReportDataRepository.java
- src/main/java/org/recap/service/formatter/datadump/SCSBXmlFormatterService.java
- src/test/java/org/recap/repository/MatchingInstitutionBibRepositoryUT.java
- src/test/java/org/recap/repository/ReportDataRepositoryUT.java
- src/test/java/org/recap/service/formatter/datadump/SCSBXmlFormatterServiceUT.java
RECAP-344 - Added matching institution bibid for scsb xml - data dump
> RECAP-344 - Added matching institution bibid for scsb xml - data dump

- src/main/java/org/recap/service/formatter/datadump/SCSBXmlFormatterService.java
Updated 001 values to have bibliographic id
> Updated 001 values to have bibliographic id

- src/main/java/org/recap/service/formatter/datadump/MarcXmlFormatterService.java
- src/test/java/org/recap/service/formatter/datadump/MarcXmlFormatterServiceUT.java
RECAP-414 - Added owning institution ids for data dump
> RECAP-414 - Added owning institution ids for data dump

- src/main/java/org/recap/service/formatter/datadump/SCSBXmlFormatterService.java
RECAP-344 - added check for matching institution id if there is no record in report table
> RECAP-344 - added check for matching institution id if there is no record in report table

- src/main/java/org/recap/service/formatter/datadump/SCSBXmlFormatterService.java
> Added matching inst id log

- src/main/resources/application-junit.properties
> Updated the junit property

- src/main/resources/application-dev.properties
- src/main/resources/application-junit.properties
- src/main/resources/application-local-container.properties
- src/main/resources/application-tst.properties
- src/main/resources/application-uat.properties
Updated the urls with container names
> Updated the urls with container names

- src/main/java/org/recap/service/formatter/datadump/MarcXmlFormatterService.java
- src/test/java/org/recap/service/formatter/datadump/MarcXmlFormatterServiceUT.java
RECAP-543 - Added subfield 3 to the datafield 876
> RECAP-543 - Added subfield 3 to the datafield 876

- src/main/resources/application-dev.properties
- src/main/resources/application-junit.properties
- src/main/resources/application-local-container.properties
- src/main/resources/application-local.properties
- src/main/resources/application-tst.properties
- src/main/resources/application-uat.properties
Updated datadump.records.per.file to take the value from external properties file
> Updated datadump.records.per.file to take the value from external properties file

- src/main/java/org/recap/RecapConstants.java
- src/main/java/org/recap/service/formatter/datadump/MarcXmlFormatterService.java
RECAP 698  - 001 tag issue fix
> RECAP 698  - 001 tag issue fix

- src/main/resources/application.properties
RECAP-703 : Added application.properties with default parameters.
> RECAP-703 : Added application.properties with default parameters.

- src/main/java/org/recap/camel/EtlDataLoadProcessor.java
- src/main/java/org/recap/camel/RecordProcessor.java
RECAP-757 : Added failure report if bib content not having holding content while dataload
> RECAP-757 : Added failure report if bib content not having holding content while dataload

- src/main/java/org/recap/RecapConstants.java
- src/main/java/org/recap/camel/datadump/DataExportEmailProcessor.java
- src/main/java/org/recap/camel/datadump/routebuilder/DataExportReportFtpRouteBuilder.java
- src/main/java/org/recap/service/executor/datadump/AbstractDataDumpExecutorService.java
- src/main/java/org/recap/service/executor/datadump/DataDumpExecutorInterface.java
- src/main/java/org/recap/service/executor/datadump/DataDumpExecutorService.java
Recap-800 Changed report filenames for datadump
> Recap-800 Changed report filenames for datadump

- src/main/java/org/recap/camel/datadump/consumer/SCSBXMLFormatActiveMQConsumer.java
Fixed logger info to accept parameters
> Fixed logger info to accept parameters

- src/main/java/org/recap/RecapConstants.java
- src/main/java/org/recap/config/SwaggerInterceptor.java
- src/main/java/org/recap/service/RestHeaderService.java
- src/main/java/org/recap/spring/ApplicationContextProvider.java
- src/main/java/org/recap/spring/PropertyValueProvider.java
- src/main/java/org/recap/spring/SwaggerAPIProvider.java
- src/main/resources/application.properties
Fixed Authentication Issue for scsb-etl Datadump service.
> Fixed Authentication Issue for scsb-etl Datadump service.
